version: "3.6"
services:
  mysql:
    image: 'mysql'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=masuk123
  testapp:
    image: 'golang:1.13.7-alpine3.11 AS builder'
    ports:
      - '8999:8999'
    environment:
      - NODE_ENV=development
    restart:
      on-failure
networks:
  default:
    external:
      name: test