// Code generated by MockGen. DO NOT EDIT.
// Source: modules/request/converter/interface.go

// Package converter is a generated GoMock package.
package converter

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// GetCurrUSD mocks base method.
func (m *MockInterface) GetCurrUSD(header *http.Header, usd **float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrUSD", header, usd)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetCurrUSD indicates an expected call of GetCurrUSD.
func (mr *MockInterfaceMockRecorder) GetCurrUSD(header, usd interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrUSD", reflect.TypeOf((*MockInterface)(nil).GetCurrUSD), header, usd)
}
