// Code generated by MockGen. DO NOT EDIT.
// Source: modules/request/efishery/interface.go

// Package efishery is a generated GoMock package.
package efishery

import (
	http "net/http"
	reflect "reflect"

	models "github.com/bagustyo92/auth/modules/request/models"
	gomock "github.com/golang/mock/gomock"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// GetPriceLists mocks base method.
func (m *MockInterface) GetPriceLists(header *http.Header, priceList **[]models.Price) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPriceLists", header, priceList)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetPriceLists indicates an expected call of GetPriceLists.
func (mr *MockInterfaceMockRecorder) GetPriceLists(header, priceList interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPriceLists", reflect.TypeOf((*MockInterface)(nil).GetPriceLists), header, priceList)
}
